# Please Note that this file IS NOT PRODUCTION READY.
# It's only dedicated to local test & try

version: '3.5'

services:
  ara-postgresql-db-source:
    image: "postgres:12"
    restart: always
    ports:
      - 6432:5432
    environment:
      - POSTGRES_DB=ara
      - POSTGRES_USER=changeme
      - POSTGRES_PASSWORD=changeme
    networks:
      - db_net
  ara-postgresql-db-target:
    image: "postgres:12"
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=ara
      - POSTGRES_USER=changeme
      - POSTGRES_PASSWORD=changeme
    networks:
      - db_net
  ara-postgresql-api:
    image: docker.io/decathlon/ara-api
    restart: always
    environment:
      - ARA_DATABASE_TARGET=postgresql
      - ARA_DATABASE_HOST=ara-postgresql-db-source:5432
      - ARA_DATABASE_NAME=ara
      - ARA_DATABASE_USERNAME=changeme
      - ARA_DATABASE_PASSWORD=changeme
    networks:
      - db_net
      - api_net
    depends_on:
      - ara-postgresql-db-source
  ara-postgresql-mig-api:
    image: docker.io/decathlon/ara-api
    restart: always
    environment:
      - ARA_DATABASE_TARGET=postgresql
      - ARA_DATABASE_HOST=ara-postgresql-db-target:5432
      - ARA_DATABASE_NAME=ara
      - ARA_DATABASE_USERNAME=changeme
      - ARA_DATABASE_PASSWORD=changeme
      - ARA_DATABASE_LIQUIBASE_ENABLED=false
      - ARA_DATABASE_HBM2DDL=create-drop
    networks:
      - db_net
      - api_net
    depends_on:
      - ara-postgresql-db-target
  waiter-postgresql-api:
    image: aligor/wait-for-url
    command: ["--url", "http://ara-postgresql-api:8000/actuator/info", "--retries", "20", "--delay", "3000"]
    networks:
      - api_net
    depends_on:
      - ara-postgresql-api
  waiter-postgresql-mig-api:
    image: aligor/wait-for-url
    command: ["--url", "http://ara-postgresql-mig-api:8000/actuator/info", "--retries", "20", "--delay", "3000"]
    networks:
      - api_net
    depends_on:
      - ara-postgresql-mig-api
networks:
  db_net:
  api_net:
