# Please Note that this file IS NOT PRODUCTION READY.
# It's only dedicated to local test & try

version: '3.5'

services:
  ara-db-source:
    image: "mysql:5.7"
    restart: always
    ports:
      - 4306:3306
    environment:
      - MYSQL_DATABASE=ara
      - MYSQL_USER=changeme
      - MYSQL_PASSWORD=changeme
      - MYSQL_ROOT_PASSWORD=to_change
    networks:
      - db_net
  ara-db-target:
    image: "mysql:5.7"
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=ara
      - MYSQL_USER=changeme
      - MYSQL_PASSWORD=changeme
      - MYSQL_ROOT_PASSWORD=to_change
    networks:
      - db_net
  ara-api:
    image: docker.io/decathlon/ara-api
    restart: always
    environment:
      - ARA_DATABASE_TARGET=mysql
      - ARA_DATABASE_HOST=ara-db-source:3306
      - ARA_DATABASE_NAME=ara
      - ARA_DATABASE_USERNAME=changeme
      - ARA_DATABASE_PASSWORD=changeme
    networks:
      - db_net
      - api_net
    depends_on:
      - ara-db-source
  ara-mig-api:
    image: docker.io/decathlon/ara-api
    restart: always
    environment:
      - ARA_DATABASE_TARGET=mysql
      - ARA_DATABASE_HOST=ara-db-target:3306
      - ARA_DATABASE_NAME=ara
      - ARA_DATABASE_USERNAME=changeme
      - ARA_DATABASE_PASSWORD=changeme
      - ARA_DATABASE_LIQUIBASE_ENABLED=false
      - ARA_DATABASE_HBM2DDL=create-drop
    networks:
      - db_net
      - api_net
    depends_on:
      - ara-db-target
  waiter-api:
    image: aligor/wait-for-url
    command: ["--url", "http://ara-api:8080/actuator/info", "--retries", "20", "--delay", "3000"]
    networks:
      - api_net
    depends_on:
      - ara-api
  waiter-mig-api:
    image: aligor/wait-for-url
    command: ["--url", "http://ara-mig-api:8080/actuator/info", "--retries", "20", "--delay", "3000"]
    networks:
      - api_net
    depends_on:
      - ara-mig-api
networks:
  db_net:
  api_net:
