# Please Note that this file IS NOT PRODUCTION READY.
# It's only dedicated to local test & try

version: '3.5'

services:
  ara-api:
    image: docker.io/decathlon/ara-api
    restart: always
    environment:
      - ARA_DATABASE_TARGET=h2
      - ARA_DATABASE_HOST=file
      - ARA_DATABASE_NAME=/app/data/ara-db;AUTO_SERVER=TRUE
    networks:
      - api_net
    volumes:
      - ./db_h2:/app/data
  ara-mig-api:
    image: docker.io/decathlon/ara-api
    restart: always
    environment:
      - ARA_DATABASE_TARGET=h2
      - ARA_DATABASE_HOST=file
      - ARA_DATABASE_NAME=/app/data/ara-db-mig;AUTO_SERVER=TRUE
      - ARA_DATABASE_LIQUIBASE_ENABLED=false
      - ARA_DATABASE_HBM2DDL=update
    networks:
      - api_net
    volumes:
      - ./db_h2_mig:/app/data
  waiter-api:
    image: aligor/wait-for-url
    command: ["--url", "http://ara-api:8080/actuator/info", "--retries", "20", "--delay", "3000"]
    networks:
      - api_net
    depends_on:
      - ara-api
  waiter-mig-api:
    image: aligor/wait-for-url
    command: ["--url", "http://ara-mig-api:8080/actuator/info", "--retries", "20", "--delay", "3000"]
    networks:
      - api_net
    depends_on:
      - ara-mig-api
networks:
  api_net:
