# Please Note that this file IS NOT PRODUCTION READY.
# It's only dedicated to local test & try

version: '3.5'

services:
  ara-db-source:
    image: "mysql:5.7"
    restart: always
    ports:
      - 4306:3306
    environment:
      - MYSQL_DATABASE=ara
      - MYSQL_USER=changeme
      - MYSQL_PASSWORD=changeme
      - MYSQL_ROOT_PASSWORD=to_change
    networks:
      - db_net
  ara-db-target:
    image: "mysql:5.7"
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=ara
      - MYSQL_USER=changeme
      - MYSQL_PASSWORD=changeme
      - MYSQL_ROOT_PASSWORD=to_change
    networks:
      - db_net
  ara-api:
    image: docker.io/decathlon/ara-api
    restart: always
    environment:
      - DATABASE_TYPE=mysql
      - DATABASE_HOST=ara-db-source:3306
      - DATABASE_NAME=ara
      - DATABASE_USER=root
      - DATABASE_PASSWORD=to_change
      - CLIENT_URL="http://localhost:80/"
    networks:
      - db_net
      - api_net
    depends_on:
      - ara-db-source
  ara-mig-api:
    image: docker.io/decathlon/ara-api
    restart: always
    environment:
      - DATABASE_TYPE=mysql
      - DATABASE_HOST=ara-db-target:3306
      - DATABASE_NAME=ara
      - DATABASE_USER=root
      - DATABASE_PASSWORD=to_change
      - LIQUIBASE_ACTIVE=false
      - HBM2DDL=create-drop
      - CLIENT_URL="http://localhost:80/"
    networks:
      - db_net
      - api_net
    depends_on:
      - ara-db-target
  waiter-api:
    image: aligor/wait-for-url
    command: ["--url", "http://ara-api:8080/actuator/info", "--retries", "20", "--delay", "3000"]
    networks:
      - api_net
    depends_on:
      - ara-api
  waiter-mig-api:
    image: aligor/wait-for-url
    command: ["--url", "http://ara-mig-api:8080/actuator/info", "--retries", "20", "--delay", "3000"]
    networks:
      - api_net
    depends_on:
      - ara-mig-api
networks:
  db_net:
  api_net:
