# Please Note that this file IS NOT PRODUCTION READY.
# It's only dedicated to local test & try

version: '3.5'

services:
  ara-mysql-db-source:
    image: "mysql:8"
    restart: always
    ports:
      - 4306:3306
    environment:
      - MYSQL_DATABASE=ara
      - MYSQL_USER=changeme
      - MYSQL_PASSWORD=changeme
      - MYSQL_ROOT_PASSWORD=to_change
    networks:
      - db_net
  ara-mysql-db-target:
    image: "mysql:8"
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=ara
      - MYSQL_USER=changeme
      - MYSQL_PASSWORD=changeme
      - MYSQL_ROOT_PASSWORD=to_change
    networks:
      - db_net
  ara-mysql-api:
    image: docker.io/decathlon/ara-api
    restart: always
    environment:
      - ARA_DATABASE_TARGET=mysql
      - ARA_DATABASE_HOST=ara-mysql-db-source:3306
      - ARA_DATABASE_NAME=ara
      - ARA_DATABASE_USERNAME=changeme
      - ARA_DATABASE_PASSWORD=changeme
    networks:
      - db_net
      - api_net
    depends_on:
      - ara-mysql-db-source
  ara-mysql-mig-api:
    image: docker.io/decathlon/ara-api
    restart: always
    environment:
      - ARA_DATABASE_TARGET=mysql
      - ARA_DATABASE_HOST=ara-mysql-db-target:3306
      - ARA_DATABASE_NAME=ara
      - ARA_DATABASE_USERNAME=changeme
      - ARA_DATABASE_PASSWORD=changeme
      - ARA_DATABASE_LIQUIBASE_ENABLED=false
      - ARA_DATABASE_HBM2DDL=create-drop
    networks:
      - db_net
      - api_net
    depends_on:
      - ara-mysql-db-target
  waiter-mysql-api:
    image: aligor/wait-for-url
    command: ["--url", "http://ara-mysql-api:8000/actuator/info", "--retries", "20", "--delay", "3000"]
    networks:
      - api_net
    depends_on:
      - ara-mysql-api
  waiter-mysql-mig-api:
    image: aligor/wait-for-url
    command: ["--url", "http://ara-mysql-mig-api:8000/actuator/info", "--retries", "20", "--delay", "3000"]
    networks:
      - api_net
    depends_on:
      - ara-mysql-mig-api
networks:
  db_net:
  api_net:
