version: "3"

services:
  ara-api:
    image: maven:3-adoptopenjdk-16
    working_dir: /app
    volumes:
      - ./api:/app
      - m2_home:/root/.m2
    command: ['/bin/bash', '-c', 'mvn -Pdev ${OPTIONAL_CLEAN} install && mvn -Pdev spring-boot:run -pl api']
#    ports:
#      - 8080:8080
  ara-web-ui:
    image: node:12
    working_dir: /app
    volumes:
      - ./web-ui:/app
    command: ['/bin/bash','-c','npm install && npm run start']
#    ports:
#      - 8081:8080
  ara-gw:
    image: maven:3-adoptopenjdk-16
    working_dir: /app
    volumes:
      - ./gateway:/app
      - m2_home:/root/.m2
      - "${CONF_PATH:-../../ara-conf}:/config:ro"
    command: ['/bin/bash', '-c', 'mvn spring-boot:run -X -P dev -Dspring-boot.run.jvmArguments="-Dspring.profiles.active=dev,authent"']
    ports:
      - 80:8080


volumes: 
  m2_home:
