# Please Note that this file IS NOT PRODUCTION READY.
# It's only dedicated to local test & try

version: '3.5'

services:
  ara-db:
    image: "postgres:12"
    restart: always
    environment:
      - POSTGRES_DB=ara
      - POSTGRES_USER=changeme
      - POSTGRES_PASSWORD=changeme
    networks:
      - db_net
    ports:
      - 5432:5432
  ara-api:
    image: "decathlon/ara-api:${API_VERSION:-latest}"
    restart: always
    environment:
      - ARA_DATABASE_TARGET=postgresql
      - ARA_DATABASE_HOST=ara-db:5432
      - ARA_DATABASE_NAME=ara
      - ARA_DATABASE_USERNAME=changeme
      - ARA_DATABASE_PASSWORD=changeme
      - INFO_APP_VERSION=DEV
      - ARA_CLIENTBASEURL=localhost:8081
    networks:
      - web_net
      - db_net
  ara-web-ui:
    image: "decathlon/ara-web-ui:${WEB_UI_VERSION:-latest}"
    restart: always
    networks:
      - web_net
  ara-gw:
    image: "decathlon/ara-gw:${GW_VERSION:-latest}"
    environment:
      - FEATURE_FLIPPING_AUTHENT_OAUTH_ENABLED=false
    volumes:
      - "${SECRETS_PATH}:/app/config:ro"
    ports:
      - 80:8080
    networks:
      - web_net
networks:
  web_net:
  db_net:

# validate: validate the schema, makes no changes to the database.
# update: update the schema.
# create: creates the schema, destroying previous data.
# create-drop: drop the schema when the SessionFactory is closed explicitly, typically when the application is stopped.
