version: "3"

services:
  back:
    image: maven:3-adoptopenjdk-16
    working_dir: /app
    volumes:
      - ./api:/app
      - m2_home:/root/.m2
    command: ['/bin/bash', '-c', 'mvn -Pdev install && mvn -Pdev spring-boot:run -pl api']
    ports:
      - 8080:8080
  front:
    image: node:12
    working_dir: /app
    volumes:
      - ./web-ui:/app
    command: ['/bin/bash','-c','npm install && npm run start']
    ports:
      - 8081:8081
    environment:
      - "ARA_API_HOST=back"

volumes: 
  m2_home:
