# Please Note that this file IS NOT PRODUCTION READY.
# It's only dedicated to local test & try

version: '3'

services:
  ara-db:
    image: "postgres:12"
    restart: unless-stopped
    environment:
      - POSTGRES_DB=ara
      - POSTGRES_USER=changeme
      - POSTGRES_PASSWORD=changeme
    networks:
      db_net: {}
    ports:
      - 5432:5432
  ara-api:
    image: "decathlon/ara-api:${API_VERSION:-latest}"
    restart: unless-stopped
    environment:
      - ARA_DATABASE_TARGET=postgresql
      - ARA_DATABASE_HOST=ara-db:5432
      - ARA_DATABASE_NAME=ara
      - ARA_DATABASE_USERNAME=changeme
      - ARA_DATABASE_PASSWORD=changeme
      - INFO_APP_VERSION=DEV
    networks:
      web_net: {}
      db_net: {}
  ara-web-ui:
    image: "decathlon/ara-web-ui:${WEB_UI_VERSION:-latest}"
    restart: unless-stopped
    environment:
      - ARA_API_HOST=ara-api
    networks:
      web_net: {}
    ports:
      - 7000:7000
  oauth2-dev-server:
    image: "decathlon/ara-oads:${OADS_VERSION:-latest}"
    pull_policy: always
    restart: unless-stopped
    networks:
      web_net:
        aliases:
          - oauth2.dev.localhost
    ports:
      - 9000:9000
networks:
  web_net:
  db_net:
