{{- if and (not .Values.database.external) (not .Values.database.embedded) }}
{{- $name := printf "%s-%s-%s" .Release.Name .Chart.Name "db" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/name: {{ include "ara.name" . }}
    helm.sh/chart: {{ include "ara.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/component: {{ $name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ara.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: {{ $name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ara.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: {{ $name }}
    spec:
      containers:
      - name: {{ $name }}
        image: "postgres:12"
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: {{ include "ara.database.secret.name" . }}
              key: {{ include "ara.database.secret.databasenamekey" . }}
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "ara.database.secret.name" . }}
              key: {{ include "ara.database.secret.usernamekey" . }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "ara.database.secret.name" . }}
              key: {{ include "ara.database.secret.passwordkey" . }}
        ports:
        - containerPort: {{ .Values.db.port }}
        {{- if .Values.db.resources }}
        resources:
{{ toYaml .Values.db.resources | indent 10 }}
        {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
spec:
  ports:
  - port: {{ .Values.db.port }}
  selector:
    app.kubernetes.io/name: {{ include "ara.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: {{ $name }}
  clusterIP: None
{{- end }}
