{{- if .Values.ingress.enabled }}
{{- $name := printf "%s-%s" .Chart.Name "ingress" -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/name: {{ include "ara.name" . }}
    helm.sh/chart: {{ include "ara.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/component: {{ $name }}
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ printf "%s-%s" .Chart.Name "ui" }}
          servicePort: http-port
        path: /
      - backend:
          serviceName: {{ printf "%s-%s" .Chart.Name "api" }}
          servicePort: http-port
        path: /api
      - backend:
          serviceName: {{ printf "%s-%s" .Chart.Name "api" }}
          servicePort: http-port
        path: /actuator/info
      - backend:
          serviceName: {{ printf "%s-%s" .Chart.Name "api" }}
          servicePort: http-port
        path: /auth
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end -}}
{{- end }}
