apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ara.configmap.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "ara.name" . }}
    helm.sh/chart: {{ include "ara.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/component: configuration
data:
  database_host: {{ include "ara.db.host" . | quote }}
  database_type: {{ .Values.database.type }}
  database_options: {{ .Values.database.options | quote }}
  liquibase_active: {{ .Values.database.liquibaseActive | quote }}
  app_url: {{ .Values.api.appUrl }}
  api_url: {{ printf "%s-api.%s.svc.cluster.local:%.0f" .Chart.Name .Release.Namespace .Values.api.port }}
  application-auth.properties: |
{{ .Values.api.authProperties | indent 4 }}
  application-custom.properties: |
{{ .Values.api.customProperties | indent 4 }}
