= Contributing

Before contributing, please read carefully, complete and sign our [Contributor Licence Agreement](contributor-licence-agreement.adoc).

When contributing to this repository, please first discuss the change you wish to make via issue or any other available method with the owners of this repository before making a change.

Please note we have a [code of conduct](code-of-conduct.adoc), please follow it in all your interactions with the project.

== Pull Request Process

. Ensure any install or build dependencies are removed before the end of the layer when doing a
   build.
. Update the README.adoc with details of changes to the interface, this includes new environment
   variables, exposed ports, useful file locations and container parameters.
. Increase the version numbers in any examples files and the README.adoc to the new version that this
   Pull Request would represent. The versioning scheme we use is [SemVer](http://semver.org/).
. Squash all your commits before creating the Pull Request. (One commit per feature/issue)
. You may merge the Pull Request in once you have the sign-off of two other developers, or if you
   do not have permission to do that, you may request the second reviewer to merge it for you.