---

# Logs

logging:
  level:
    reactor:
      netty: INFO


# actuator
server:
  port: 9000
management:
  server:
    port: 9001
  endpoints:
    web:
      base-path: /actuatorgw
      exposure:
        include: health, info

---

# >>> DEFAULT VALUES
# Remember values can be overriden by env vars (ARA_API_HOST, ... )

spring:
  profiles:
    active: __profiles.from.maven__

ara:
  api:
    host: localhost
    port: 8000
    managementport: 8001
  ui:
    host: localhost
    port: 7000



# <<< END DEFAULT VALUES

---

# Routes

spring:
  cloud:
    # >> A proxy for ARA
    gateway:
      routes:
        - id: back
          uri: "http://${ara.api.host}:${ara.api.port}"
          predicates:
            - Path=/api/**,/demo-files/**
          filters:
           - TokenRelay=
        - id: backmanagement
          uri: "http://${ara.api.host}:${ara.api.managementport}"
          predicates:
            - Path=/actuator/**
        - id: front
          uri: "http://${ara.ui.host}:${ara.ui.port}"
          predicates:
            - Path=/**

---
# oauth conf
# override with stuff like
#   file:/config/oauth-client-credentials,optional:file:/config/oauth-resourceserver.yml for example
spring:
  config:
    import: config-oauth.yaml,optional:file:/app/config/config-custom.yaml

---

# Feature flipping

feature-flipping:
  authent:
    oauth:
      features:
        authorization-code: true
        client-credentials: true

#    user-token:
#      enable: true


