---

# Logs

logging:
  level:
    reactor:
      netty: INFO


# actuator

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /actuatorgw
      exposure:
        include: health, info

---

# >>> DEFAULT VALUES
# Remember values can be overriden by env vars (ARA_API_HOST, ... )

spring:
  profiles:
    active: __profiles.from.maven__

ara:
  api:
    host: ara-api
    port: 8080
    managementport: 9090
  ui:
    host: ara-web-ui
    port: 8080



# <<< END DEFAULT VALUES

---

# Routes

spring:
  cloud:
    # >> A proxy for ARA
    gateway:
      routes:
        - id: back
          uri: "http://${ara.api.host}:${ara.api.port}"
          predicates:
            - Path=/api/**,/demo-files/**
          filters:
           - TokenRelay=
        - id: backmanagement
          uri: "http://${ara.api.host}:${ara.api.managementport}"
          predicates:
            - Path=/actuator/**
        - id: front
          uri: "http://${ara.ui.host}:${ara.ui.port}"
          predicates:
            - Path=/**

---
# oauth conf
# override with stuff like
#   file:/config/oauth-client-credentials,optional:file:/config/oauth-resourceserver.yml for example
spring:
  config:
    import: oauth.yml

---

# Feature flipping

feature-flipping:
  authent:
    oauth:
      features:
        authorization-code: true
        client-credentials: true

#    user-token:
#      enable: true


