---

# Oauth
spring:
  security:
    oauth2:
      # >> the authorization_code conf
      client:
        registration:
          fedid:
            client-name: fed id
            client-id: "${custom.client_id}"
            client-secret: "${custom.client_secret}"
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile
        provider:
          fedid:
            issuer-uri: "${custom.issuer-uri}"

      # >> the resource server conf for client credentials conf
      resourceserver:
        jwt:
          jwk-set-uri: "${custom.jwk-set-uri}"

