info:
    app:
        name: ARA core-api
    api:
        version: @project.version@
ara:
    logging:
        mode: logging-console
spring:
    profiles:
        include: @spring.profiles.active@,${ara.logging.mode}
    config:
        import: config-database.yaml,optional:config-custom.yaml
springdoc:
    packagesToScan: com.decathlon.ara
    pathsToMatch: /api/**
    use-management-port: true
management:
    info:
        env:
            enabled: true
    server:
        port: 9090
    endpoints:
        web:
            exposure:
                include: health, info, openapi, swaggerui
