ara:
  database:
    name: ara
    # Default database
    target: @ara.default.database@
    # Default credentials
    username: changeme
    password: changeme
    # Database structure
    # Managed by liquibase by default
    liquibase:
      enabled: true
    hbm2ddl: none
spring:
  h2:
    console:
      enabled: false
  liquibase:
    enabled: ${ara.database.liquibase.enabled}
    change-log: classpath:/db/changelog/db.changelog-master-${ara.database.target}.yaml
  profiles:
    include: db-${ara.database.target}
  datasource:
    username: ${ara.database.username}
    password: ${ara.database.password}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        hbm2ddl:
          # Managed by liquidbase
          auto: ${ara.database.hbm2ddl}
        globally_quoted_identifiers: false
---
spring:
  config:
    activate:
      on-profile: dev
  # In dev we use hibernate DDL and not liquibase
  jpa:
    properties:
      hibernate:
        format_sql: false
        hbm2ddl:
          auto: create-drop
    show-sql: false
  liquibase:
    enabled: false
