apiVersion: apps/v1
kind: Deployment
metadata:
  name: ara-db
  labels:
    app: ara-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ara-db
  template:
    metadata:
      labels:
        app: ara-db
    spec:
      containers:
      - name: ara-db
        image: ara-db
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: ara-database
              key: database
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ara-database
              key: root-password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: ara-database
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ara-database
              key: password
        ports:
        - containerPort: 3306
        resources:
          limits:
            memory: "1Gi"
            cpu: "800m"

---
apiVersion: v1
kind: Service
metadata:
  name: ara-db
spec:
  ports:
  - port: 3306
  selector:
    app: ara-db
  clusterIP: None