version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/code/back"
    update_schedule: "daily"
    default_reviewers:
      - "decathlon/ara"
    default_assignees:
      - "JulienBarlet"
      - "dktsni"

  - package_manager: "javascript"
    directory: "/code/front"
    update_schedule: "live"
    default_reviewers:
      - "decathlon/ara"
    default_assignees:
      - "JulienBarlet"
      - "dktsni"
