# Override default app name
# nameOverride:

##
## API Configuration
##
api:
    image:
        registry: docker.io
        repository: decathlon/ara-api
        # tag:
        imagePullPolicy: IfNotPresent
    replicas: 1
    annotations: {}
    resources: {}
        # We usually recommend not to specify default resources and to leave this as a conscious
        # choice for the user. This also increases chances charts run on environments with little
        # resources, such as Minikube. If you do want to specify resources, uncomment the following
        # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
        # limits:
        #  cpu: 100m
        #  memory: 128Mi
        # requests:
        #  cpu: 100m
        #  memory: 128Mi
    port: 8080
    # Used to redirect on the app by email service among others
    appUrl: ara.test
    authProperties: ""
    # Use an existing secret
    propertiesExistingSecret:
        enabled: false
        # secretName: nameofsecret
        # authPropertiesKey: application-auth.properties
        # customPropertiesKey: application-custom.properties
    customProperties: ""
    # sideCarContainer:
    # volumes:

##
## UI Configuration
##
ui:
    image:
        registry: docker.io
        repository: decathlon/ara-web-ui
        # tag:
        imagePullPolicy: IfNotPresent
    replicas: 1
    annotations: {}
    resources: {}
        # We usually recommend not to specify default resources and to leave this as a conscious
        # choice for the user. This also increases chances charts run on environments with little
        # resources, such as Minikube. If you do want to specify resources, uncomment the following
        # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
        # limits:
        #  cpu: 100m
        #  memory: 128Mi
        # requests:
        #  cpu: 100m
        #  memory: 128Mi
    port: 80

##
## Postgresql Database Configuration
##
database:
    embedded: true
    # type mysql is suported when embedded is false
    type: h2
    # When embedded is false you can provide default cluster database or external database:
    external: false
    # When external is true you can set the host of database
    # host:
    # Active liquibase update
    liquibaseActive: true
    # Name of the database
    name: ara
    options: ''
    # Set if no existing secret
    username: ara
    password: changeme
    # Use an existing secret
    existingSecret:
        enabled: false
        # secretName: nameofsecret
        # usernameKey: username
        # passwordKey: password
        # databaseNameKey: database

##
## Internal DB Configuration
##
db:
    resources: {}
        # We usually recommend not to specify default resources and to leave this as a conscious
        # choice for the user. This also increases chances charts run on environments with little
        # resources, such as Minikube. If you do want to specify resources, uncomment the following
        # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
        # limits:
        #  cpu: 100m
        #  memory: 128Mi
        # requests:
        #  cpu: 100m
        #  memory: 128Mi
    port: 3306

## Allowing use of ingress controllers
## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/
##
ingress:
    enabled: false
    # Set url to access to ara by ingress
    host: ara.test
    annotations: {}
    tls: {}

loadBalancer:
    enabled: true
    # loadBalancerIP:
