package com.decathlon.ara.web.rest;

import com.codahale.metrics.annotation.Timed;
import com.decathlon.ara.service.ProjectService;
import com.decathlon.ara.service.dto.ignore.ScenarioIgnoreSourceDTO;
import com.decathlon.ara.service.dto.scenario.ScenarioSummaryDTO;
import com.decathlon.ara.service.exception.BadRequestException;
import com.decathlon.ara.service.exception.NotFoundException;
import com.decathlon.ara.web.rest.util.HeaderUtil;
import com.decathlon.ara.web.rest.util.ResponseUtil;
import com.decathlon.ara.Entities;
import com.decathlon.ara.service.ScenarioService;
import java.io.File;
import java.io.IOException;
import java.util.List;
import javax.validation.Valid;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.io.FileUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;

import static com.decathlon.ara.web.rest.util.RestConstants.PROJECT_API_PATH;

/**
 * REST controller for managing Scenarios.
 */
@Slf4j
@RestController
@RequestMapping(ScenarioResource.PATH)
@RequiredArgsConstructor(onConstructor = @__(@Autowired))
public class ScenarioResource {

    private static final String NAME = Entities.SCENARIO;
    static final String PATH = PROJECT_API_PATH + "/" + NAME + "s";

    @NonNull
    private final ScenarioService scenarioService;

    @NonNull
    private final ProjectService projectService;

    /**
     * POST to move upload the scenario set of a test code.
     *
     * @param projectCode the code of the project in which to work
     * @param sourceCode  the source-code determining the location of the files that are uploaded
     * @param json        the report.json file as generated by a cucumber --dry-run
     * @return OK on success, INTERNAL_SERVER_ERROR on processing error
     */
    @PostMapping("/upload/{sourceCode}")
    @Timed
    public ResponseEntity<Void> uploadCucumber(@PathVariable String projectCode, @PathVariable String sourceCode, @Valid @RequestBody String json) {
        try {
            scenarioService.uploadCucumber(projectService.toId(projectCode), sourceCode, json);
            return ResponseEntity.ok().build();
        } catch (BadRequestException e) {
            log.error("Failed to upload Cucumber scenarios for source code {}", sourceCode, e);
            return ResponseUtil.handle(e);
        }
    }

    @PostMapping("/upload-postman/{sourceCode}")
    @Timed
    public ResponseEntity<Void> uploadPostman(@PathVariable String projectCode,
                                              @PathVariable String sourceCode,
                                              @RequestParam("file") MultipartFile file) {
        File tempZipFile = null;
        try {
            tempZipFile = File.createTempFile("ara_scenario_upload_", ".zip");
            tempZipFile.deleteOnExit();
            file.transferTo(tempZipFile);
            scenarioService.uploadPostman(projectService.toId(projectCode), sourceCode, tempZipFile);
            return ResponseEntity.ok().build();
        } catch (BadRequestException e) {
            log.error("Failed to upload ZIP file containing Postman requests for source code {}", sourceCode, e);
            return ResponseUtil.handle(e);
        } catch (IOException e) {
            log.error("Failed to upload ZIP file containing Postman requests for source code {}", sourceCode, e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .headers(HeaderUtil.exception(Entities.SCENARIO, e))
                    .build();
        } finally {
            FileUtils.deleteQuietly(tempZipFile);
        }
    }

    /**
     * @param projectCode the code of the project in which to work
     * @return all scenarios that have no associated functionalities or have wrong or nonexistent functionality identifier
     */
    @GetMapping("/without-functionalities")
    @Timed
    public ResponseEntity<List<ScenarioSummaryDTO>> getAllWithFunctionalityErrors(@PathVariable String projectCode) {
        try {
            return ResponseEntity.ok().body(scenarioService.findAllWithFunctionalityErrors(projectService.toId(projectCode)));
        } catch (NotFoundException e) {
            return ResponseUtil.handle(e);
        }
    }

    /**
     * @param projectCode the code of the project in which to work
     * @return for each source (API, Web...), a count of ignored&amp;total scenarios and a list of ignored scenarios by feature file
     */
    @GetMapping("/ignored")
    @Timed
    public ResponseEntity<List<ScenarioIgnoreSourceDTO>> getIgnoredScenarioCounts(@PathVariable String projectCode) {
        try {
            return ResponseEntity.ok().body(scenarioService.getIgnoredScenarioCounts(projectService.toId(projectCode)));
        } catch (NotFoundException e) {
            return ResponseUtil.handle(e);
        }
    }

}
