{{- if not .Values.database.existingSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ara.database.secret.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "ara.name" . }}
    helm.sh/chart: {{ include "ara.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/component: db-secret
type: Opaque
data:
  {{ template "ara.database.secret.usernamekey" }}: {{ .Values.database.password | b64enc | quote }}
  {{ template "ara.database.secret.passwordkey" }}: {{ .Values.database.username | b64enc | quote }}
  {{ template "ara.database.secret.databasenamekey" }}: {{ .Values.database.name | b64enc | quote }}
{{- end }}
