{{- $name := printf "%s-%s" .Chart.Name "ui" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/name: {{ include "ara.name" . }}
    helm.sh/chart: {{ include "ara.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/component: {{ $name }}
spec:
  replicas: {{ .Values.ui.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ara.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: {{ $name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ara.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: {{ $name }}
    spec:
      containers:
      - name: {{ $name }}
        image: "{{ .Values.image.registry }}/ara-web-ui:{{ .Chart.Version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "ara.configmap.name" . }}
              key: api_url
        ports:
        - containerPort: {{ .Values.ui.port }}
          name: http-port
        readinessProbe:
          httpGet:
            path: /api/projects
            port: {{ .Values.ui.port }}
          initialDelaySeconds: 40
          timeoutSeconds: 2
          periodSeconds: 3
          failureThreshold: 2
        {{- if .Values.ui.resources }}
        resources:
{{ toYaml .Values.ui.resources | indent 10 }}
        {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
spec:
  {{- if .Values.loadBalancer.enabled }}
  type: LoadBalancer
  {{- if .Values.loadBalancer.loadBalancerIP }}
  loadBalancerIP: {{ .Values.loadBalancer.loadBalancerIP }}
  {{- end }}
  {{- end }}
  ports:
  - protocol: TCP
    port: {{ .Values.ui.port }}
    targetPort: http-port
  selector:
    app.kubernetes.io/name: {{ include "ara.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: {{ $name }}
