{{- $name := printf "%s-%s" .Chart.Name "api" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/name: {{ include "ara.name" . }}
    helm.sh/chart: {{ include "ara.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: {{ $name }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ara.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: {{ $name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ara.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: {{ $name }}
    spec:
      containers:
      - name: {{ $name }}
        image: "{{ .Values.image.registry }}/ara-back:{{ .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "ara.configmap.name" . }}
              key: database_url
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name:  {{ include "ara.database.secret.name" . }}
              key: {{ include "ara.database.secret.usernamekey" . }}
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "ara.database.secret.name" .}}
              key: {{ include "ara.database.secret.passwordkey" . }}
        - name: CLIENT_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "ara.configmap.name" . }}
              key: ui_url
        - name: DATA_DB_MODE
          valueFrom:
            configMapKeyRef:
                name: {{ include "ara.configmap.name" . }}
                key: db_mode
        ports:
        - containerPort: {{ .Values.api.port }}
          name: http-port
        {{- if .Values.api.resources }}
        resources:
{{ toYaml .Values.api.resources | indent 10 }}
        {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.api.port }}
    targetPort: http-port
  selector:
    app.kubernetes.io/name: {{ include "ara.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: {{ $name }}
