= ARA's Developer Documentation

Check you are agree with the terms and conditions of contributor license agreements. <</doc/contributing/contributing.adoc#head, Contributing>>

== Getting Started

What you need:

* Docker

Optional:

* make
* Maven & Java 14
* Node 12

Below is what you will need to set up on your development machine.

```bash
cd code
```

`code` is the directory where the code is placed.

We can find 2 subdirectories:

* `api`: contains the *api server* in **maven / java 14**
* `web-ui`: contains the *web interface* in **node 12**

== Start the api

In `api` folder.

**With Docker and make**

```bash
# Install
make dkr-install
# Run
make dkr-run
```

**With maven/java 14**

```bash
# Install
make mvn-install
# Run
make mvn-run
```

ou

```bash
# Install
mvn clean install
# Run
mvn -Pdev spring-boot:run -pl server
```

NOTE: La base par défaut sans profil maven est une base h2 in memory. Les données seront perdues au redémarrage de l'application. En passant au profil `dev` via `-Pdev` la base h2 est persistée dans un fichier.

API is available at `localhost:8080`, you can check this url http://localhost:8080/actuator/info to observe the API is up.

== Start the web-ui

In `web-ui` folder.

**With Docker and make**

```bash
# Install
make dkr-install
# Run
make dkr-run
```

**With node 12**

```bash
# Install
make mpm-install
# Run
make npm-run
```

ou

```bash
# Install
npm install
# Run
npm run dev
```

WEB-UI is available at `localhost:8081`, you can check this url http://localhost:8081 to observe the web-ui is up.
