= ARA's Developer Documentation

== Getting Started in Two Minutes

Below is what you will need to set up on your development machine.

* *Create a database and start it:*
  ** Go to the folder containing the script `manage-db.sh`:  `cd <ARA_ROOT>/database/instance`, where `<ARA_ROOT>` is your project path location in your computer.
  ** (Optional) You can change your database root account's password in the `manage-db.sh` script.
  By default it is `dev_password_to_change`.
  ** Run it: `./manage-db.sh create <FOLDER_PATH_TO_PERSISTS>`, where `<FOLDER_PATH_TO_PERSISTS>` is the path where you want to save your data.
  ** (Optional) You can check that your relational database management system is up and running: `./manage-db.sh mysqladmin`
* *Build your project:*
  ** +++<u>Build the client</u>+++:
     *** Go to the client folder: `cd <ARA_ROOT>/client`
     *** Run `npm install` to install all the required dependencies
     *** Run `npm run build` to build the client
  ** +++<u>Build the server</u>+++:
     *** Run `mvn clean install -Pdev` in the `<ARA_ROOT>` folder to build the server.
     *** Bear in mind that:
         **** you can speed up the build by skipping the unit tests `mvn clean install -Pdev -Dmaven.test.skip=true`
         **** for now, your `JAVA_HOME` environment variable should point to Java 8. Make sure `mvn -v` displays this version. We're currently working (https://github.com/Decathlon/ara/pull/167) to accept all java versions above this version.
         **** later, when modifying the server, just run `mvn clean install -Pdev` in the `<ARA-ROOT>/server` folder to only compile the server, instead of rebuilding all the project.
* *Launch your project:*
  ** +++<u>Start the server</u>+++:
     *** From the root of your project, run `java -Dspring.profiles.active=dev -cp final/target/ara-<ARA_CURRENT_VERSION_SNAPSHOT>.jar -Dspring.datasource.password=<YOUR DB ACCOUNT PASS> -Dloader.main=com.decathlon.ara.AraApplication org.springframework.boot.loader.PropertiesLauncher` to launch the back-end server. This step is more suitable for integration tests rather than active development phase. +
  ** +++<u>Start the client</u>+++:
     *** Wait for the server to be up and running
     *** Run `npm run dev` in the `<ARA_ROOT>/client` folder to start the front-end server.
     *** ARA's GUI is available at http://localhost:8081.
* *(Optional) Generate the project site:*
  ** Clean your project by running `mvn clean` command from `<ARA_ROOT>`
  ** Run `mvn package site site:phase` to generate the maven site containing all the details concerning this project.
     Please note that this operation may take a while (up to 15 minutes).
  ** Open the generated `<ARA_ROOT>/target/staging/index.html` file to browse the site

More information are provided below and in linked detailed documentations.

== Technical Details of the Project

=== Modules

Follow links for module-specific documentations:

* *<<../client/README.adoc#head, client>>*: the front-end with the user experience
  (generates static files packaged as a JAR to be included in the server JAR)
* *db*: a script to create an ARA database using Docker:
  use the parameter `create` to create one database server
  with both the `ara-dev` (to run both client and server for manual tests)
  and `ara-dev-in` (for integration tests of the server project) schemas,
  or use the parameter `help` for more information about available commands
  (start, stop, destroy, mysqladmin, shell, purge)
* *doc*: <<../integrator/main/IntegratorDocumentation.adoc#head, integrator>>,
  <<../user/main/UserDocumentation.adoc#head, user>> and
  <<../developer/DeveloperDocumentation.adoc#head, developer>> documentations
* *generated-cucumber-report*: contains Cucumber feature files used to generate report files
  used on the server integration tests to run into all possible cases while indexing such reports
* *ide-resources*: IDE <<../ide-resources/eclipse/README.adoc#head, configuration for Eclipse>> and
  <<../ide-resources/intellij/README.adoc#head, configuration for IntelliJ>>
* *<<../server/README.adoc#head, server>>*: the back-end which handles the logic and communication with the database
  (depends on the `generated-cucumber-report` projects for integration tests,
  and includes the `client` project to only have one server to start in production)

=== How to View/Edit the Documentation

In order to edit and view rendered ASCII-arts (images with Ditaa and UML with PlantUML),
you need to download and install AsciidocFX + GraphViz: they contain all "plugins" like Ditaaa and PlantUML:

* Install AsciidocFX : +
  https://asciidocfx.com/#truehow-to-install-asciidocfx
* Install GraphViz: +
  http://www.graphviz.org/download/ +
  Choose eg. "Stable 2.38 Windows install packages"

Note: on the AsciidocFX page, you can see how to create UML, ASCII-art, directory-listing, math expressions, graphics...

You can open and edit the .adoc files with AsciidocFX.

Once AsciidocFX + GraphViz is installed, the AsciiDoc plugin in IntelliJ IDEA will display ASCII-art and
UML generated images for you without any further installation nor configuration. This is pretty neat.

Useful links:

* AsciiDoctor syntax: +
  https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/
* Ditaa syntax for ASCII-art: +
  http://ditaa.sourceforge.net/#usage
* PlantUML syntax for UML diagrams: +
  http://plantuml.com/sitemap-language-specification
