name: build web-ui

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │  ┌───────────── hour (0 - 23)
    #        │  │ ┌───────────── day of the month (1 - 31)
    #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        *  * * * *
    - cron: '30 1 * * 0'

jobs:
  code_app_change:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v3.4.0
        with:
          github_token: ${{ github.token }}
          paths: '["code/web-ui/**", ".github/workflows/build-web-ui.yaml"]'
          cancel_others: 'true'
          do_not_skip: '["push", "workflow_dispatch", "schedule"]'
  build-web-ui:
    needs: code_app_change
    if: ${{ needs.code_app_change.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
          persist-credentials: false # To use github token provide for semantic release
      - 
        name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: javascript
          config-file: ./.github/codeql/codeql-web-ui-config.yml

      -
        name: Add pre-push hook for semantic release git
        run: |
          cat << EOF > .git/hooks/pre-push
          #!/bin/bash
          git pull --rebase --autostash
          EOF
          chmod +x .git/hooks/pre-push

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          working_directory: ./code/web-ui
          semantic_version: 18
          dry_run: false
          extra_plugins: |
            @semantic-release/commit-analyzer@9.0.2
            @semantic-release/release-notes-generator@10.0.3
            @semantic-release/exec@6.0.2
            @semantic-release/npm@8.0.3
            @semantic-release/git@10.0.1
            @semantic-release/github@8.0.2
          extends: |
            semantic-release-monorepo
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - 
        name: Get project version
        id: getVersion
        run: |
          pushd code
          PROJECT_VERSION=$(make -s get-web-ui-version)
          popd
          echo ::set-output name=projectVersion::${PROJECT_VERSION}
      - 
        name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: code/web-ui
          args: >
            -Dsonar.projectVersion=${{ steps.getVersion.outputs.projectVersion }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - 
        name: Prepare
        id: prep
        run: |
          PUSH=FALSE
          pushd code
          APP_EXISTS=$(make -s check-web-ui-image)
          popd
          if [[ $GITHUB_REF == refs/heads/* ]]; then
            BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
            if [ "${{ github.event.repository.default_branch }}" = "$BRANCH_NAME" ] && [ "$APP_EXISTS" != 'true' ]; then
              PUSH=TRUE
            fi
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            BRANCH_NAME=$(echo ${{ github.event.pull_request.head.ref }} | sed -r 's#/+#-#g')
            if [[ $BRANCH_NAME == release-* ]]; then
              PUSH=TRUE
              SUFFIX=rc
            else
              SUFFIX=pr-${{ github.event.number }}
            fi
          fi
          echo ::set-output name=push::${PUSH}
          echo ::set-output name=suffix::${SUFFIX}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        if: ${{ steps.prep.outputs.push == 'true' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push
        run: |
          pushd code
          make build-web-ui SUFFIX=${{ steps.prep.outputs.suffix }} PUBLISH=${{ steps.prep.outputs.push }}
          popd
      - 
        name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
        with:
          category: "ara_web-ui"
