name: build web-ui

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - main

jobs:
  code_web_ui_change:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v3.4.0
        with:
          github_token: ${{ github.token }}
          paths: '["code/web-ui/**"]'
          cancel_others: 'true'
          do_not_skip: '["push", "workflow_dispatch"]'
  docker_image:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: skip_check
        run: |
          if [[ $GITHUB_REF == refs/pull/* ]]; then
            WEB_UI_EXISTS=false
          else
            pushd code
            WEB_UI_EXISTS=$(make -s check-web-ui-image)
            popd
          fi
          echo ::set-output name=should_skip::${WEB_UI_EXISTS}
  build-web-ui:
    needs:
      - code_web_ui_change
      - docker_image
    if: ${{ needs.code_web_ui_change.outputs.should_skip != 'true' && needs.docker_image.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        id: prep
        run: |
          PUSH=FALSE
          if [[ $GITHUB_REF == refs/heads/* ]]; then
            BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
            if [ "${{ github.event.repository.default_branch }}" = "$BRANCH_NAME" ]; then
              PUSH=TRUE
            fi
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            BRANCH_NAME=$(echo ${{ github.event.pull_request.head.ref }} | sed -r 's#/+#-#g')
            if [[ $BRANCH_NAME == release-* ]]; then
              PUSH=TRUE
              SUFFIX=rc
            else
              SUFFIX=pr-${{ github.event.number }}
            fi
          fi
          echo ::set-output name=push::${PUSH}
          echo ::set-output name=suffix::${SUFFIX}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        if: ${{ steps.prep.outputs.push == 'true' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        run: |
          cd code
          make build-web-ui SUFFIX=${{ steps.prep.outputs.suffix }} PUBLISH=${{ steps.prep.outputs.push }}
