name: BUILD CORE API

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  code_core-api_change:
    name: Code core-api Change Detection
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v3.4.1
        with:
          github_token: ${{ github.token }}
          paths: '["code/core-api/**"]'
          cancel_others: 'true'
          do_not_skip: '["push", "workflow_dispatch"]'
  build_core-api:
    name: Tests, Analysis and Build 
    needs: code_core-api_change
    if: ${{ needs.code_core-api_change.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK
        uses: actions/setup-java@v2.2.0
        with:
          distribution: 'adopt'
          java-version: '16'

      - name: Cache SonarCloud packages
        uses: actions/cache@v2.1.6
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v2.1.6
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build, unit test and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -f code/core-api/ -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        run: mvn -f code/core-api/ spring-boot:build-image -Dmaven.test.skip=true -Dspring-boot.build-image.imageName=decathlon/ara-core-api:${{ github.sha }}
