name: Release Candidate Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/candidate/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false # To use github token provide for semantic release
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0
      - name: Add pre-push hook for semantic release git
        run: |
          cat << EOF > .git/hooks/pre-push
          #!/bin/bash
          git pull --rebase --autostash
          EOF
          chmod +x .git/hooks/pre-push
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          working_directory: ./charts/candidate
          semantic_version: 18
          dry_run: false
          extra_plugins: |
            @semantic-release/commit-analyzer@9.0.2
            @semantic-release/release-notes-generator@10.0.3
            @semantic-release/exec@6.0.2
            @semantic-release/changelog@6.0.1
            @semantic-release/git@10.0.1
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Remove pre-push hook for chart releaser
        run: rm -rf .git/hooks/pre-push
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Run chart-releaser
        uses: Thomgrus/chart-releaser-action@feat/manage-chart-by-chart-diff
        with:
          config: .github/cr-config.yaml
          version: v1.3.0
          charts_dir: charts/candidate
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
