name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/stable/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0
      - id: version
        name: Get version
        working-directory: code
        run: |
          FROM_TAG=$(git describe --tags --abbrev=0  --match "ara-stable-v*")
          CHART_VERSION=$(make -s get-chart-version TARGET_CHART=stable)
          echo ::set-output name=stable::${CHART_VERSION}
          echo ::set-output name=fromTag::${FROM_TAG}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ara-stable-${{ steps.version.outputs.stable }}
          release_name: ara-stable-${{ steps.version.outputs.stable }}
          draft: true
          prerelease: false
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          fromTag: "${{ steps.version.outputs.fromTag }}"
          toTag: "ara-stable-${{ steps.version.outputs.stable }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Changelog file
        uses: finnp/create-file-action@v1.0.0
        env:
          FILE_NAME: "charts/stable/CHANGELOG.md"
          FILE_DATA: "${{steps.github_release.outputs.changelog}}"
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Run chart-releaser
        uses: Thomgrus/chart-releaser-action@feat/manage-chart-by-chart-diff
        with:
          config: .github/cr-config.yaml
          version: v1.3.0
          charts_dir: charts/stable
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
