name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Stable chart
        run: |
          ./.github/helm-chart-stable.sh
          VERSION=$(cat charts/stable/Chart.yaml | grep version | sed -e 's/version: //')
          git commit -am "chore: auto-commit chart ${VERSION}"
          git push
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0
        env:
          CR_TOKEN: '${{ secrets.CR_TOKEN }}'
