name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/stable/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0
        env:
          CR_TOKEN: '${{ secrets.CR_TOKEN }}'
