name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/stable/**'

jobs:
  check_rc:
    runs-on: ubuntu-latest
    outputs:
      rc: ${{ steps.check_rc_step.outputs.rc }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Check if rc
        id: check_rc_step
        run: |
          CHART_VERSION=$(cat charts/stable/Chart.yaml | grep version | sed -e 's/version: //')
          if [[ $CHART_VERSION == *-rc* ]]; then
            echo ::set-output name=rc::true
          else
            echo ::set-output name=rc::false
  release:
    runs-on: ubuntu-latest
    if: ${{ needs.check_rc.outputs.rc != 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        env:
          CR_TOKEN: '${{ secrets.CR_TOKEN }}'
  pr_release:
    runs-on: ubuntu-latest
    if: ${{ needs.check_rc.outputs.rc == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        id: prep
        run: |
          DEV_VERSION=$(cat charts/dev/Chart.yaml | grep version | sed -e 's/version: //')
          VERSION=$(echo "$DEV_VERSION" | sed -e 's/-rc.*//')
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=rc::${DEV_VERSION}
      - name: Upgrade stable with dev
        run: ./.github/helm-chart-stable.sh
      - name: Create PR with changes
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.CR_TOKEN }}
          commit-message: "chore: Release Charts stable ${{ steps.prep.outputs.version }}"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: "helm/stable/${{ steps.prep.outputs.version }}"
          body: "Auto-release stable from ${{ steps.prep.outputs.rc }}"
          delete-branch: true
          title: "chore: Release Charts stable ${{ steps.prep.outputs.version }}"
