name: Upgrade Release

on:
  push:
    branches:
      - release/*.*.*

jobs:
  upgrade-release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Prepare
        id: prep
        run: |
          RELEASE_BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
          RELEASE=${RELEASE_BRANCH#release-}
          DEV_VERSION=$(cat charts/dev/Chart.yaml | grep version | sed -e 's/version: //')
          VERSION=$(echo "$DEV_VERSION" | sed -e 's/-rc.*//')
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=release::${RELEASE}
      -
        name: Upgrade version
        if: steps.prep.outputs.version != steps.prep.outputs.release
        run: |
          cd code
          make update-version VERSION=${{ steps.prep.outputs.release }}
          cd ..
      -
        name: Create PR with changes
        id: cpr
        if: steps.prep.outputs.version != steps.prep.outputs.release
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.CR_TOKEN }}
          commit-message: "chore: ⬆️ Upgrade to ${{ steps.prep.outputs.release }}"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: "upgrade/${{ steps.prep.outputs.release }}"
          body: "Auto-update to release/${{ steps.prep.outputs.release }}"
          delete-branch: true
          title: "chore: ⬆️ Upgrade to ${{ steps.prep.outputs.release }}"
      - 
        name: Check outputs
        if: steps.prep.outputs.version != steps.prep.outputs.release
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
